-- ============================================================================
-- InvoiceAI — multi-user schema (run once in the Supabase SQL editor)
-- ============================================================================
-- Identity = the signed-in Google account. The same Google consent grants
-- gmail.readonly, so the user's email is both their login and their mailbox.

-- 1) Users -------------------------------------------------------------------
create table if not exists public.users (
    email         text primary key,
    name          text,
    picture       text,
    refresh_token text,                        -- Fernet-encrypted Google refresh token
    created_at    timestamptz not null default now(),
    last_login    timestamptz
);

-- 2) Invoices ----------------------------------------------------------------
-- If you already have an `invoices` table from the single-user version, run the
-- ALTER + index below instead of CREATE.
create table if not exists public.invoices (
    id                  bigint generated by default as identity primary key,
    user_email          text not null references public.users(email) on delete cascade,
    email_id            text not null,         -- Gmail message id (or "<id>__N" for multi-invoice mails)
    service_name        text,
    date                text,
    amount              double precision,
    currency            text,
    category            text,
    invoice_id          text,
    description         text,
    email_subject       text,
    scanned_account     text,
    subscription_period text default 'monthly',
    created_at          timestamptz not null default now()
);

-- Per-user uniqueness: the upsert conflict target is (user_email, email_id).
create unique index if not exists invoices_user_email_email_id_key
    on public.invoices (user_email, email_id);

-- Fast per-user dashboard reads.
create index if not exists invoices_user_email_idx
    on public.invoices (user_email);

-- ---------------------------------------------------------------------------
-- MIGRATING an existing single-user `invoices` table:
--   alter table public.invoices add column if not exists user_email text;
--   -- backfill existing rows to whoever owned them, then:
--   alter table public.invoices alter column user_email set not null;
--   -- drop the old email_id-only unique constraint if present, then create the
--   -- composite unique index above.
-- ---------------------------------------------------------------------------

-- NOTE on RLS: this app talks to Supabase with the service-role key and enforces
-- per-user isolation in application code (every query filters by user_email).
-- RLS is therefore optional here; add policies later as defense-in-depth if you
-- ever expose Supabase directly to clients.
